version: '3.1'

services:
  elasticsearch:
    container_name: els
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports: 
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
